baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "Sabrosita Milano "
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Chi siamo"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Workshop"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Ricette"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Contattaci"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/sab_canva.png"
  logo_footer = "images/logo-footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/icon_sab.jpg"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
 
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/grafica.sab.jpeg"
    heading               = "I CUPCAKES PIÙ ESOTICI DI MILANO"
    
    primary_button        = "Workshop"
    primary_button_url    = "portfolio"
    secondary_button      = "Contattaci "
    secondary_button_url  = "contact"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "I NOSTRI SERVIZI E WORKSHOP"
    subtitle  = "Anima la tua festa con attività di cucina e non solo!"
    view_project = "Dimmi di più"
    more_works = "MORE WORKS"
    scroll_down = "scorri in basso"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "PRENOTA ORA!"
    primary_button      = "Contattaci"
    primary_button_url  = "contact"
    secondary_button    = "Workshop"
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contatti"
      address = "V.le Col di Lana, 12, 20136 Milano MI"
      phone   = "340 843 8937"
      email   = "mailsabrosita"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "La mia storia"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Workshop"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Ricette"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contattaci"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/sabrosita_milano/"
      # Footer Service
     
      [params.footer.back_to_top]
        description = "Torna  su"
